version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_inventory_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/:/var/lib/mysql
